openapi: 3.0.3

info:
  title: KC Web backend API
  description: Test project for API documentation and codegen
  version: 1.0.0
  contact:
    name: Andres Garcia
    email: andres-gr@users.noreply.github.com

servers:
  - url: http://localhost:4000/api/v1
    description: Testing v1 API

tags:
  - name: Places
    description: Place management

  - name: Projects
    description: Project management

  - name: Todos
    description: Todo management

  - name: Users
    description: User management

components:
  responses:
    NoItemFound:
      description: No item/s found for given ID
      content: 
        application/json:
          schema:
            $ref: '#/components/schemas/BaseErrorResponse'

    UnprocessableEntity:
      description: Incorrect or missing values
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseErrorResponse'

  parameters:
    paramsId:
      in: path
      name: id
      required: true
      description: Item ID value
      schema:
        type: string

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # - - - - - - - - - - - - - - - - - - - - - bodies start - - - - - - - - - - - - - - - - - - - - - - - # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  requestBodies:
    PlacesBody:
      description: New place object body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PlaceBody'

    TodoBody:
      description: Todo text content
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TodoContent'

    SignupBody:
      description: Signup body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SignupContent'

    LoginBody:
      description: Login body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginContent'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # - - - - - - - - - - - - - - - - - - - - - bodies end - - - - - - - - - - - - - - - - - - - - - - - - # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # - - - - - - - - - - - - - - - - - - - - - schemas start - - - - - - - - - - - - - - - - - - - - - - - # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  schemas:
    BaseResponse:
      type: string
      example: Response message

    BaseErrorResponse:
      type: object
      required:
        - message
      properties:
        errors:
          type: array
          items:
            type: object
            additionalProperties: true
        message:
          $ref: '#/components/schemas/BaseResponse'
        status:
          type: integer

    ID:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: Unique ID for the item
          example: 1847kjdsasdfk

    PlaceBody:
      type: object
      required:
        - image
        - title
        - address
        - userId
        - location
      properties:
        image:
          type: string
          description: Image url
          example: http://image.stock.com/images/place/1
        title:
          type: string
          description: Title of the place
          example: This is the place
        description:
          type: string
          description: Additional info of the place
          example: Image meta description
        address:
          type: string
          description: Corresponding address of the location
          example: The description info of the image
        userId:
          type: string
          description: ID of the user that created the place
          example: 1023kljlasdfja0
        location:
          type: object
          description: Object containing the coordinates of the place
          required:
            - lat
            - lng
          properties:
            lat:
              type: number
              description: Latitude of the place
              example: -21.0309383
            lng:
              type: number
              description: Longitude of the place
              example: 23.0182198

    Place:
      allOf:
        - $ref: '#/components/schemas/ID'
        - $ref: '#/components/schemas/PlaceBody'

    GetPlacesResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        places:
          type: array
          items:
            $ref: '#/components/schemas/Place'

    PostPlaceResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        place:
          $ref: '#/components/schemas/Place'

    GetPlaceResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        place:
          $ref: '#/components/schemas/Place'

    PatchPlaceResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        place:
          $ref: '#/components/schemas/Place'

    DeletePlaceResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        place:
          $ref: '#/components/schemas/Place'

    Project:
      type: object
      required:
        - id
        - company
        - author
      properties:
        id:
          type: string
          example: 37014kdjasf01
        company:
          type: string
          example: Funahus LLC
        author:
          type: string
          example: John Smiff

    GetProjectResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        project:
          $ref: '#/components/schemas/Project'

    Todo:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: string
          example: id_1234qwert
        text:
          type: string
          example: Todo text content

    TodoContent:
      type: object
      properties:
        text:
          type: string
          example: A new todo text content

    GetTodosResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        todos:
          type: array
          items:
            $ref: '#/components/schemas/Todo'

    PostTodoResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        todo:
          $ref: '#/components/schemas/Todo'

    PatchTodoResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        todo:
          $ref: '#/components/schemas/Todo'

    DeleteTodoResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        todo:
          $ref: '#/components/schemas/Todo'

    UserBody:
      type: object
      required:
        - email
        - image
        - name
        - places
      properties:
        email:
          type: string
          description: User email
          example: jon@smiff.com
        image:
          type: string
          description: Profile image url for the user
          example: http://image.stock.com/images/profile/1
        name:
          type: string
          example: John Smiff
        places:
          type: integer
          description: Number of places shared
          example: 3

    User:
      allOf:
        - $ref: '#/components/schemas/ID'
        - $ref: '#/components/schemas/UserBody'

    SignupContent:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    LoginContent:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    UserPasswords:
      type: object
      properties:
        ids:
          type: string
      additionalProperties: true
      description: Key value pairs of userId to hashed password

    GetUsersResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'

    SignupResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        user:
          $ref: '#/components/schemas/User'

    LoginResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/BaseResponse'
        user:
          $ref: '#/components/schemas/User'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # - - - - - - - - - - - - - - - - - - - - - schemas end - - - - - - - - - - - - - - - - - - - - - - - - # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # - - - - - - - - - - - - - - - - - - - - - paths start - - - - - - - - - - - - - - - - - - - - - - - - # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

paths:
  /places:
    get:
      description: Get all places
      summary: Get all places
      tags:
        - Places
      responses:
        200:
          description: Retrieved all places successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetPlacesResponse'
    post:
      description: Create a new place
      summary: Create a new place
      requestBody:
        description: New place object body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceBody'
      tags:
        - Places
      responses:
        201:
          description: Created a new place successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostPlaceResponse'
        422:
          $ref: '#/components/responses/UnprocessableEntity'

  /places/{id}:
    parameters:
      - $ref: '#/components/parameters/paramsId'
    get:
      description: Get a single place
      summary: Get a single place
      tags:
        - Places
      responses:
        200:
          description: Retrieve a single place successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetPlaceResponse'
        404:
          $ref: '#/components/responses/NoItemFound'

    patch:
      description: Update a single place
      summary: Update a single place
      tags:
        - Places
      requestBody:
        description: Update place object body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceBody'
      responses:
        200:
          description: Updated a single place successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchPlaceResponse'
        404:
          $ref: '#/components/responses/NoItemFound'
        422:
          $ref: '#/components/responses/UnprocessableEntity'

    delete:
      description: Delete a single place
      summary: Delete a single place
      tags:
        - Places
      responses:
        200:
          description: Deleted a single place successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletePlaceResponse'
        404:
          $ref: '#/components/responses/NoItemFound'

  /places/user/{id}:
    parameters:
      - $ref: '#/components/parameters/paramsId'
    get:
      description: Get all places of user
      summary: Get all places of user
      tags:
        - Places
      responses:
        200:
          description: Retrieve all places of a user successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetPlacesResponse'
        404:
          $ref: '#/components/responses/NoItemFound'

  /project:
    get:
      description: Get a random project info
      summary: Get a random project info
      tags:
        - Projects
      responses:
        200:
          description: A random project object
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetProjectResponse'

  /todos:
    get:
      description: Get all todos
      summary: Get all todos
      tags:
        - Todos
      responses:
        200:
          description: Returns all todos
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetTodosResponse'
    post:
      description: Submit a new todo
      summary: Submit a new todo
      tags:
        - Todos
      requestBody:
        $ref: '#/components/requestBodies/TodoBody'
      responses:
        201:
          description: Added a new todo successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/PostTodoResponse'

  /todos/{id}:
    parameters:
      - $ref: '#/components/parameters/paramsId'
    patch:
      description: Update todo with selected ID
      summary: Update todo with selected ID
      tags:
        - Todos
      requestBody:
        $ref: '#/components/requestBodies/TodoBody'
      responses:
        200:
          description: Updated todo with selected ID successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/PatchTodoResponse'
    delete:
      description: Delete todo with selected ID
      summary: Delete todo with selected ID
      tags:
        - Todos
      responses:
        200:
          description: Delete todo with selected ID successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteTodoResponse'

  /users:
    get:
      description: Get list of users
      summary: Get list of users
      tags:
        - Users
      responses:
        200:
          description: Retrieved list of users successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'

  /signup:
    post:
      description: Send a signup request
      summary: Send a signup request
      tags:
        - Users
      requestBody:
        $ref: '#/components/requestBodies/SignupBody'
      responses:
        201:
          description: Signup was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        403:
          description: Email already in use
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        422:
          $ref: '#/components/responses/UnprocessableEntity'

  /login:
    post:
      description: Send a login request
      summary: Send a login request
      tags:
        - Users
      requestBody:
        $ref: '#/components/requestBodies/LoginBody'
      responses:
        200:
          description: Login was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        401:
          description: Credentials incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # - - - - - - - - - - - - - - - - - - - - - paths end - - - - - - - - - - - - - - - - - - - - - - - - - # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
